development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: ‘http://kenfaye.herokuapp.com/faye ‘
  secret_token: “cc21f841f77268133986a34012aed6b346755bbca0eb06cd028389816c11ded0”
  signature_expiration: 86400 # one day
